### ISSUE TITLE
[FF3.5.5 & IE7] On refresh, loader img stays on refresh

### ISSUE THREAD

**Issue by Tim-Wils** [darkwing/LazyLoad#1]
To recreate this problem, start the demo > scroll to the middle of the page > hit F5. The loader image stays and the cached images that were there before the refresh don't come up.
Maybe this issue is there in other browsers as well, but I didn't got the chance to check that.

**Comment by darkwing** [comment]
This has been fixed in the current version -- a scroll event may be fired to do the first check.
