### ISSUE TITLE
LazyLoad 2.1 - Unable to get value of the property 'defaultView'

### ISSUE THREAD

**Issue by drewgg** [darkwing/LazyLoad#3]
Mootools: 1.3.2  ( http://mootools.net/core/7c56cfef9dddcf170a5d68e3fb61cfd7 ) 
LazyLoad: 2.1 ( http://mootools.net/forge/download/lazyload/2.1 )

Load code: 

[head]

```
    <script language="javascript" type="text/javascript" src="mootools.js"></script>
    <script language="javascript" type="text/javascript" src="LazyLoad.js"></script>
    <script language="javascript" type="text/javascript">
        window.addEvent('domready', function() {
            var lazyloader = new LazyLoad({
                range: 200,
                realSrcAttribute: "data-src",
                useFade: true,
                elements: 'img',
                container: window
            });
        });
    </script>
```

[body]

```
<img width="100" height="100" src="blank.gif" data-src="testimage.png" />
```

LazyLoad wouldn't work for me with that set up (only tested in FF6 and IE9). IE9 was throwing this error:

```
Unable to get value of the property 'defaultView': object is null or undefined mootools.js, line 333 character 2
```

Which is this code in mootools.js: 

```
var g=Element.getDocument(this).defaultView,
```

I'm not sure if I'm doing something wrong but after downgrading to LazyLoad 2.0 (I nabbed your code from http://davidwalsh.name/dw-content/lazyload-2.0.php) everything started working without issue.

**Comment by darkwing** [comment]
I'll have a look at this tonight.  My demo uses 1.3.1 so there could be a difference.  In the mean time, using document.body could work.

**Comment by darkwing** [comment]
drewgg - can you put this in a JS fiddle?  I can't duplicate this issue with 1.3.2 from Google CDN.

**Comment by drewgg** [comment]
Sure!

http://jsfiddle.net/drewgg/yt3e3/8/  <-- non-working (tested in Chrome 13, FF6, IE9)
http://jsfiddle.net/drewgg/yt3e3/7/  <-- working (tested in Chrome 13, FF6, IE9)

Both those links are to basically the same code, (mootools 1.3.2, lazyload 2.1, lazyload 2.0, then the domready event) just in the non-working one lazyload 2.0 is commented out, and in the working one lazyload 2.1 is commented out.
